# For more information see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
