server:
  port: 8080
  servlet.context-path: /pcs

management:
  server.port: 9000
  endpoints.web:
    exposure.include: "*"
    # allow to call actuator from Swagger UI running on a different (application) port
    cors:
      allowed-origins: http://localhost:${server.port}
      allowed-methods: "*"
  endpoint.health.show-details: always
  health:
    defaults.enabled: true
    circuitbreakers.enabled: true

  endpoint.sbom:
    # to generate SBOM just build with maven using "sbom" profile
    application.location: optional:classpath:META-INF/sbom/application.cdx.json

logging:
  file:
    name: logs/application.log
  level:
    root: info
    org.springframework: warn
    org.hibernate: warn
    mirogaudi.productcatalog: info

spring:
  application.name: product-catalog-service

  http:
    serviceclient:
      frankfurter-rates-service:
        base-url: https://api.frankfurter.dev
        connect-timeout: 2s
        read-timeout: 2s

  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        connection.provider_disables_autocommit: true

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/db/pcs;AUTO_SERVER=TRUE
    username: sa
    password: # empty
    hikari:
      auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
  circuitbreaker:
    instances:
      cb-frankfurter-rates-service:
        # for details see https://resilience4j.readme.io/docs/circuitbreaker
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: true

# Product catalog service (pcs)
pcs:
  base-currency-code: EUR
  cache:
    enabled: true
    rates-cache.evict:
      # Run at 16:01 CET every Monday till Friday
      cron: 0 1 16 ? * MON-FRI
      zone: CET
