spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: create-drop

    properties:
      javax.persistence.schema-generation:
        create-source: metadata
        scripts:
          action: create
          create-target: target/classes/db/create_schema.sql
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true

logging:
  level:
    root: info
    org.hibernate.stat: info
    mirogaudi.productcatalog: debug
