server:
  port: 8080
  servlet.context-path: /pcs

management:
  server.port: 9000
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  health.defaults.enabled: true

logging:
  level:
    root: info
    org.springframework: error
    mirogaudi.productcatalog: info

spring:
  application.name: product-catalog-service

  jpa:
    generate-ddl: false

    hibernate.ddl-auto: none

    properties:
      hibernate:
        connection.provider_disables_autocommit: true

    open-in-view: false

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./target/db/pcs;AUTO_SERVER=TRUE
    username: sa
    password: # empty

    hikari:
      auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

springdoc:
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

# Product catalog service (pcs)
pcs:
  # Base currency
  base-currency-code: EUR

  # Rates service
  rates:
    service.url: https://api.frankfurter.app

    cache.evict:
      cron: 0 1 16 * * MON-FRI
      zone: CET
