server:
  port: 8080
  servlet.context-path: /pcs

spring:
  application.name: product-catalog-service

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none

    open-in-view: false

    properties:
      hibernate.connection.provider_disables_autocommit: true

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pcs
    username: sa
    password: # empty

    hikari.auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: info

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true

springdoc:
  enable-native-support: true
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

# Product catalog service (pcs)
pcs:
  # Base currency
  base-currency-code: EUR

  # Rates service
  rates:
    service.url: https://frankfurter.app

    cache.evict:
      cron: 0 1 16 * * MON-FRI
      zone: CET
