server:
  port: 8080
  servlet.context-path: /pcs

spring:
  application.name: product-catalog-service

  jpa:
    generate-ddl: false
    open-in-view: false

    hibernate.ddl-auto: none

    properties:
      hibernate.connection.provider_disables_autocommit: true

  flyway:
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pcs
    username: sa
    password: # empty

    hikari.auto-commit: false

  h2.console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: info

springdoc.swagger-ui:
  tags-sorter: alpha
  operations-sorter: alpha

# Product catalog service (pcs)
pcs:
  # Base currency
  base-currency-code: EUR

  # Rates service
  rates:
    service.url: https://frankfurter.app
    cache.evict:
      cron: 0 1 16 * * MON-FRI
      zone: CET
