logging:
  level:
    root: info
    org.springframework: info
    mirogaudi.productcatalog: debug

spring:
  jpa:
    show_sql: true
    hibernate.ddl-auto: validate
    properties:
      # generates initial db schema creation script
      jakarta.persistence.schema-generation:
        create-source: metadata
        scripts:
          action: create
          create-target: target/classes/db/generated_create_schema.sql
      hibernate:
        format_sql: true
        generate_statistics: true
