package mirogaudi.productcatalog.domain;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import org.hibernate.proxy.HibernateProxy;

import java.util.Objects;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Base entity, defines id and implements base equals and hashCode methods.
 */
@MappedSuperclass
@NoArgsConstructor
@SuperBuilder
@Getter
@Setter
@ToString
public class BaseEntity {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @SuppressFBWarnings(value = "EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS",
        justification = "Method was generated by JPA Buddy")
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null) {
            return false;
        }

        Class<?> oEffectiveClass = o instanceof HibernateProxy oHibernateProxy
            ?
            oHibernateProxy.getHibernateLazyInitializer().getPersistentClass()
            :
            o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy thisHibernateProxy
            ?
            thisHibernateProxy.getHibernateLazyInitializer().getPersistentClass()
            :
            this.getClass();
        if (thisEffectiveClass != oEffectiveClass) {
            return false;
        }

        BaseEntity that = (BaseEntity) o;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public int hashCode() {
        return this instanceof HibernateProxy hibernateProxy
            ?
            hibernateProxy.getHibernateLazyInitializer().getPersistentClass().hashCode()
            :
            getClass().hashCode();
    }

}
