create table category
(
    id        bigint generated by default as identity,
    name      varchar(128) not null unique,
    parent_id bigint,
    primary key (id)
);

create table product
(
    id                bigint generated by default as identity,
    name              varchar(256)   not null unique,
    original_currency varchar(3)     not null,
    original_price    numeric(38, 2) not null,
    currency          varchar(3)     not null,
    price             numeric(38, 2) not null,
    primary key (id)
);

create table product_category
(
    category_id bigint not null,
    product_id  bigint not null
);

alter table if exists category
    add constraint FK2y94svpmqttx80mshyny85wqr
    foreign key (parent_id)
    references category;

alter table if exists product_category
    add constraint FKkud35ls1d40wpjb5htpp14q4e
    foreign key (category_id)
    references category;

alter table if exists product_category
    add constraint FK2k3smhbruedlcrvu6clued06x
    foreign key (product_id)
    references product;
