### Actuator Health
GET http://localhost:9000/actuator/health
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received '${type}'`);
    });

    client.test("Status is UP", function () {
        const status = response.body.status;
        client.assert(status === "UP", `Expected 'UP' but received '${status}'`);
    });
%}
