# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java_CI_with_Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven wrapper generating code coverage report
        run: ./mvnw -B package -Pcode-coverage-report

      - name: Generate JaCoCo badges
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-coverage-badge: false
          generate-coverage-endpoint: true
          generate-branches-endpoint: true

      - name: Commit JaCoCo Badges
        uses: EndBug/add-and-commit@v8
        with:
          add: '*.json'
          default_author: github_actions
          message: 'Update JaCoCo badges'
